### ISSUE TITLE
Feature request : Allow to pass environment variables from Csp Object 

### ISSUE THREAD

**Issue by gcuisinier** [aquasecurity/aqua-operator#7]
Hello,

We want to install Aqua in a secure Network without direct access to Internet, but by Using an enterprise Proxy.
And if I am not wrong, for that we need to pass HTTP_PROXY Environment variables to the AquaServer.

But by using the Csp object, it seems not possible to provide user provided variables  

```yaml
apiVersion: operator.aquasec.com/v1alpha1
kind: AquaCsp
metadata:
  name: aqua
spec:
  infra:
    platform: openshift
    requirements: true
  registry:
...
  database:
  ...
  gateway:
...
  server:
    replicas: 1
    service: LoadBalancer
  adminPassword: Password1
  licenseToken: null
```

Do you thing it can be possible to add a way to provide environment variables from litteral, secret or config map ?

```yaml
apiVersion: operator.aquasec.com/v1alpha1
kind: AquaCsp
metadata:
  name: aqua
spec:
  infra:
    platform: openshift
    requirements: true
  server:
    replicas: 1
    service: LoadBalancer
  env:
  - name : "HTTP_PROXY"
    value : "DirectValue"
  - name : "HTTP_PROXY"
    valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  - name : "NO_PROXY"
    configMapKeyRef:
              name: myconfig
              key: no_proxy"
```

and propagate them to the underlying AquaServer / DeploymentConfig object?
